### ISSUE TITLE
ToDO List

### ISSUE THREAD

**Issue by ericololo** [Limentinus/ericdomenech.de#5]
Questions:
what is 

MENUE:

- what is static?
- what is dynamic?
-> using the same buttons for Work-Site? (A,B,C)
if not -> how does it look ? Dropdown? (why?, for what? -> image USER!)

Bob:
- [ ] Built first proto-type-setup / basic
- [ ] -> links

Eric:
- [ ] check google fonts
- [ ] Asset for Work -> wie soll der Datensatz für ein Werk aussehen?
